name: Check meeting page (daemon)

on:
  # Handmatig starten met keuze voor testmodus
  workflow_dispatch:
    inputs:
      test_mode:
        description: "TEST-modus: stuur push bij GEEN verandering (1=aan, 0=uit)"
        required: false
        default: "0"
  # Back-up start (voor het geval self-dispatch faalt)
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write   # voor state.json commits
  actions: write    # om zichzelf opnieuw te starten

concurrency:
  group: meeting-checker-daemon
  cancel-in-progress: true

jobs:
  loop:
    runs-on: ubuntu-latest
    timeout-minutes: 355          # ~5u55 (GitHub-hosted limiet ~6u)

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run loop (quiet hours + random interval + optional TEST-mode)
        env:
          # --- checker envs ---
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          TARGET_URL: ${{ secrets.TARGET_URL }}
          SITE_USERNAME: ${{ secrets.SITE_USERNAME }}
          SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
          USERNAME_FIELD: ${{ secrets.USERNAME_FIELD }}
          PASSWORD_FIELD: ${{ secrets.PASSWORD_FIELD }}
          EXTRA_FIELDS_JSON: ${{ secrets.EXTRA_FIELDS_JSON }}
          TEXT_TO_FIND: ${{ secrets.TEXT_TO_FIND }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          JITTER_SECONDS_MAX: "10"

          # --- stille uren ---
          QUIET_TZ: "Europe/Amsterdam"
          QUIET_START: "00:00"
          QUIET_END:   "06:32"

          # --- random interval (aanpasbaar) ---
          MIN_SLEEP_SEC: "60"   # 1 min
          MAX_SLEEP_SEC: "300"  # 5 min

          # --- TEST-modus bron: input of repo variable ---
          INPUT_TEST_MODE: ${{ github.event.inputs.test_mode }}
          VARS_TEST_MODE:  ${{ vars.TEST_MODE }}
        run: |
          set -e
          END=$(( $(date +%s) + 20700 ))   # ~5u45

          # Bepaal effectieve TEST-modus:
          # 1) workflow_dispatch input, anders 2) repo variable TEST_MODE, anders 0
          TEST_MODE="${INPUT_TEST_MODE:-${VARS_TEST_MODE:-0}}"
          echo "TEST_MODE=${TEST_MODE}"

          git config user.email "actions@users.noreply.github.com"
          git config user.name "github-actions"

          random_sleep () {
            local min="${MIN_SLEEP_SEC:-60}"
            local max="${MAX_SLEEP_SEC:-300}"
            local dur
            if [ "$max" -le "$min" ]; then
              dur="
