name: Daily summary

on:
  schedule:
    - cron: "0 6 * * *"   # 06:00 UTC → 08:00 NL in zomertijd (07:00 in wintertijd)
  workflow_dispatch: {}

permissions:
  actions: read
  contents: read

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install requests
      - name: Send daily summary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          WORKFLOW_FILE: "check.yml"   # pad/naam van je checker workflow
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python daily_summary.py
