name: Daily summary

on:
  # 18:00 NL-tijd met zomer-/wintertijd:
  # - 16:00 UTC (zomertijd, UTC+2)
  # - 17:00 UTC (wintertijd, UTC+1)
  schedule:
    - cron: "0 16 * * *"
    - cron: "0 17 * * *"
  workflow_dispatch: {}

permissions:
  actions: read
  contents: read

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install requests
      - name: Send daily summary
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          WORKFLOW_FILE: "check.yml"                 # pas aan als je checker-workflow anders heet
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          LOCAL_TZ: "Europe/Amsterdam"
          LOCAL_HOUR: "12.6"
        run: python daily_summary.py
